# Generated by Django 5.1 on 2024-08-26 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cart_menu_item_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'menu_item')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menu_item')},
        ),
    ]
